-- -- Inserir admin (senha: admin123)
-- INSERT INTO users (id, name, email, password_hash, role, enabled, created_at)
-- SELECT
--     uuid_generate_v4(),
--     'Administrador',
--     'admin@email.com',
--     '$2a$12$guYy3U2GZCwD1KRWcbpRveXFzESgDynh/NAPrjlVHr2gAVdwBRXse',
--     'ADMIN',
--     TRUE,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@email.com');