-- -- Tabela de solicitações
-- CREATE TABLE IF NOT EXISTS solicitations (
--                                              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     client_id UUID NOT NULL REFERENCES users(id),
--
--     -- Status e step
--     status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
--     current_step INTEGER DEFAULT 0,
--
--     -- Step 1 - Dados básicos
--     service_type VARCHAR(20),
--     title VARCHAR(80),
--     description VARCHAR(1000),
--
--     -- Step 2 - Endereço
--     cep VARCHAR(8),
--     number VARCHAR(20),
--     complement VARCHAR(100),
--     street VARCHAR(255),
--     neighborhood VARCHAR(100),
--     city VARCHAR(100),
--     state VARCHAR(2),
--
--     -- Step 3 - Confirmação
--     priority VARCHAR(10),
--     preferred_date DATE,
--     estimated_value DECIMAL(15,2),
--     terms_accepted BOOLEAN,
--
--     -- Auditoria
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     submitted_at TIMESTAMP,
--     analyzed_at TIMESTAMP,
--     analyzed_by UUID REFERENCES users(id),
--     analysis_comment VARCHAR(1000)
--     );
--
-- -- Índices para performance
-- CREATE INDEX idx_solicitations_client_id ON solicitations(client_id);
-- CREATE INDEX idx_solicitations_status ON solicitations(status);
-- CREATE INDEX idx_solicitations_state ON solicitations(state);
-- CREATE INDEX idx_solicitations_created_at ON solicitations(created_at);
--
--
-- -- -- Tabela de solicitações (H2 compatible)
-- -- CREATE TABLE IF NOT EXISTS solicitations (
-- --                                              id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
-- --     client_id UUID NOT NULL,
-- --
-- --     -- Status e step
-- --     status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
-- --     current_step INTEGER DEFAULT 0,
-- --
-- --     -- Step 1 - Dados básicos
-- --     service_type VARCHAR(20) CHECK (service_type IN ('INSTALLATION', 'MAINTENANCE', 'INSPECTION')),
-- --     title VARCHAR(80),
-- --     description VARCHAR(1000),
-- --
-- --     -- Step 2 - Endereço
-- --     cep VARCHAR(8),
-- --     number VARCHAR(20),
-- --     complement VARCHAR(100),
-- --     street VARCHAR(255),
-- --     neighborhood VARCHAR(100),
-- --     city VARCHAR(100),
-- --     state VARCHAR(2),
-- --
-- --     -- Step 3 - Confirmação
-- --     priority VARCHAR(10) CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
-- --     preferred_date DATE,
-- --     estimated_value DECIMAL(15,2),
-- --     terms_accepted BOOLEAN,
-- --
-- --     -- Auditoria
-- --     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- --     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- --     submitted_at TIMESTAMP,
-- --     analyzed_at TIMESTAMP,
-- --     analyzed_by UUID,
-- --     analysis_comment VARCHAR(1000),
-- --
-- --     FOREIGN KEY (client_id) REFERENCES users(id),
-- --     FOREIGN KEY (analyzed_by) REFERENCES users(id)
-- --     );
-- --
-- -- -- Índices para performance
-- -- CREATE INDEX IF NOT EXISTS idx_solicitations_client_id ON solicitations(client_id);
-- -- CREATE INDEX IF NOT EXISTS idx_solicitations_status ON solicitations(status);
-- -- CREATE INDEX IF NOT EXISTS idx_solicitations_state ON solicitations(state);
-- -- CREATE INDEX IF NOT EXISTS idx_solicitations_created_at ON solicitations(created_at);