-- -- CLIENT 1 - João Silva (SP)
-- INSERT INTO users (id, name, email, password_hash, role, enabled, created_at)
-- SELECT
--     uuid_generate_v4(),
--     'João Silva',
--     'joao@email.com',
--     '$2a$10$8G8J8K8L8M8N8O8P8Q8R8S8T8U8V8W8X8Y8Z8A8B8C8D8E8F8G8H8I',
--     'CLIENT',
--     TRUE,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'joao@email.com');
--
-- -- CLIENT 2 - Maria Souza (MG)
-- INSERT INTO users (id, name, email, password_hash, role, enabled, created_at)
-- SELECT
--     uuid_generate_v4(),
--     'Maria Souza',
--     'maria@email.com',
--     '$2a$10$8G8J8K8L8M8N8O8P8Q8R8S8T8U8V8W8X8Y8Z8A8B8C8D8E8F8G8H8I',
--     'CLIENT',
--     TRUE,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'maria@email.com');
--
-- -- CLIENT 3 - Pedro Santos (RJ)
-- INSERT INTO users (id, name, email, password_hash, role, enabled, created_at)
-- SELECT
--     uuid_generate_v4(),
--     'Pedro Santos',
--     'pedro@email.com',
--     '$2a$10$8G8J8K8L8M8N8O8P8Q8R8S8T8U8V8W8X8Y8Z8A8B8C8D8E8F8G8H8I',
--     'CLIENT',
--     TRUE,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'pedro@email.com');
--
-- -- Solicitação 1 - João Silva (SP)
-- INSERT INTO solicitations (
--     id, client_id, status, current_step,
--     service_type, title, description,
--     cep, number, complement, street, neighborhood, city, state,
--     priority, preferred_date, estimated_value, terms_accepted,
--     created_at, updated_at, submitted_at
-- )
-- SELECT
--     uuid_generate_v4(),
--     (SELECT id FROM users WHERE email = 'joao@email.com'),
--     'SUBMITTED',
--     3,
--     'INSTALLATION',
--     'Instalação de Internet Fibra Ótica',
--     'Solicitação de instalação de internet fibra ótica com velocidade de 500mb no endereço residencial.',
--     '01310000',
--     '100',
--     'Apto 101',
--     'Avenida Paulista',
--     'Bela Vista',
--     'São Paulo',
--     'SP',
--     'MEDIUM',
--     '2026-07-25',
--     150.00,
--     TRUE,
--     CURRENT_TIMESTAMP,
--     CURRENT_TIMESTAMP,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM solicitations WHERE title = 'Instalação de Internet Fibra Ótica' AND client_id = (SELECT id FROM users WHERE email = 'joao@email.com'));
--
-- -- Solicitação 2 - Maria Souza (MG)
-- INSERT INTO solicitations (
--     id, client_id, status, current_step,
--     service_type, title, description,
--     cep, number, complement, street, neighborhood, city, state,
--     priority, preferred_date, estimated_value, terms_accepted,
--     created_at, updated_at, submitted_at
-- )
-- SELECT
--     uuid_generate_v4(),
--     (SELECT id FROM users WHERE email = 'maria@email.com'),
--     'SUBMITTED',
--     3,
--     'MAINTENANCE',
--     'Manutenção de Ar Condicionado',
--     'Solicitação de manutenção preventiva em sistema de ar condicionado split. Unidade apresenta ruído anormal.',
--     '30130000',
--     '200',
--     'Sala 502',
--     'Avenida Afonso Pena',
--     'Centro',
--     'Belo Horizonte',
--     'MG',
--     'HIGH',
--     '2026-07-20',
--     350.00,
--     TRUE,
--     CURRENT_TIMESTAMP,
--     CURRENT_TIMESTAMP,
--     CURRENT_TIMESTAMP
--     WHERE NOT EXISTS (SELECT 1 FROM solicitations WHERE title = 'Manutenção de Ar Condicionado' AND client_id = (SELECT id FROM users WHERE email = 'maria@email.com'));